# General Jekyll Config
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlight: true
gems: ["jekyll-paginate"]

# Setup
title:            kulekci.net
tagline:          kulekci.net
url:              http://kulekci.net
paginate:         3
baseurl:          /
author:
  name:           Haydar KULEKCI
  url:            https://twitter.com/kulekci
  email:          haydarkulekci@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/hkulekci/hkulekci.github.com